name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    env:
      DEPTRACK_API_URL: ${{ secrets.DEPTRACK_API_URL }}
      DEPTRACK_API_KEY: ${{ secrets.DEPTRACK_API_KEY }}
      DEPTRACK_PROJECT_NAME: ${{ secrets.DEPTRACK_PROJECT_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Semgrep (SAST)
      run: docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep:latest semgrep ci --config auto --json > semgrep-report.json || true

    - name: Upload Semgrep report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: semgrep-report.json

    - name: Generate SBOM with Syft
      continue-on-error: true
      uses: anchore/sbom-action@v0.14.3
      with:
        format: cyclonedx-json
        output-file: sbom.json
        upload-artifact: false

    - name: Debug Dependency Track variables
      run: |
        echo "DEPTRACK_API_URL=${DEPTRACK_API_URL}"
        echo "DEPTRACK_API_KEY=${DEPTRACK_API_KEY}"
        echo "DEPTRACK_PROJECT_NAME=${DEPTRACK_PROJECT_NAME}"
      env:
        DEPTRACK_API_URL: ${{ secrets.DEPTRACK_API_URL }}
        DEPTRACK_API_KEY: ${{ secrets.DEPTRACK_API_KEY }}
        DEPTRACK_PROJECT_NAME: ${{ secrets.DEPTRACK_PROJECT_NAME }}

    - name: Upload SBOM to Dependency Track
      continue-on-error: true
      run: |
        curl -k -X PUT "${DEPTRACK_API_URL}/api/v1/bom" \
          -H "X-Api-Key: ${DEPTRACK_API_KEY}" \
          -F "projectName=${DEPTRACK_PROJECT_NAME}" \
          -F "autoCreate=true" \
          -F "bom=@sbom.json"

    - name: Build Docker image
      continue-on-error: true
      run: docker build -t nms:2.6.4 .

    - name: Scan Docker image with Trivy
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: nms:2.6.4
        format: cyclonedx
        output: trivy-sbom.json

    - name: Upload Trivy SBOM to Dependency Track
      continue-on-error: true
      run: |
        curl -k -X PUT "${DEPTRACK_API_URL}/api/v1/bom" \
          -H "X-Api-Key: ${DEPTRACK_API_KEY}" \
          -F "projectName=${DEPTRACK_PROJECT_NAME}" \
          -F "autoCreate=true" \
          -F "bom=@trivy-sbom.json"

    - name: Run OWASP ZAP Baseline Scan
      continue-on-error: true
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'https://crpn.ru:8084'
        cmd_options: '-a -d -g zap-report.md -r zap-report.html -w zap-warnings.txt'
        fail_action: false

    - name: Upload ZAP HTML report
      uses: actions/upload-artifact@v4
      with:
        name: zap-html-report
        path: zap-report.html
